version: '2'
services:
  ide:
    image: psharkey/intellij:latest
#    image: psharkey/netbeans-8.1:latest
    environment:
      - DISPLAY=novnc:0.0
    depends_on:
      - novnc
    networks:
      - x11
  icecc:
    image: cbarraco/icecc-daemon
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    command: iceccd -d
  novnc:  
    image: theasp/novnc:latest
    environment:
      # Adjust to your screen size
      - DISPLAY_WIDTH=1366
      - DISPLAY_HEIGHT=668
    ports:
      - "22:8080"
    networks:
      - x11
networks:
  x11:
